
package com.service_now.mysoap;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceNowSoap", targetNamespace = "http://www.service-now.com/MySOAP")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceNowSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.service-now.com/MySOAP/execute")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "execute", targetNamespace = "http://www.service-now.com/MySOAP", className = "com.service_now.mysoap.Execute")
    @ResponseWrapper(localName = "executeResponse", targetNamespace = "http://www.service-now.com/MySOAP", className = "com.service_now.mysoap.ExecuteResponse")
    public String execute();

}
